/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlch.Model.TaiKhoan;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author HiHi
 */
public class DoiMatKhau extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhau
     */
    public DoiMatKhau() {
        initComponents();
        setSize(455, 352);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Đổi Mật Khẩu");
    }
    public void setLB(String s){
        jlbManv.setText(s);
    }
     private  boolean  checkRong(){
         String matkhauc = tfMatkhaucu.getText();
         String matkhaum = tfMatkhaumoi.getText();
         String matkhauxn = tfMatkhauxn.getText();
         if(matkhauc.equals("")){
             JOptionPane.showConfirmDialog(null,"Bạn Chưa Nhập Mật Khẩu Cũ");
         }else if(matkhaum.equals("")){
             JOptionPane.showConfirmDialog(null,"Bạn Chưa Nhập Mật Khẩu Mới");
         }else if(!matkhaum.equals(matkhauxn)){
             JOptionPane.showConfirmDialog(null,"Mật Khẩu Mới Không Trùng");
         }else{
             return true;
         }
         return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbXacnhan = new javax.swing.JButton();
        jbHuy = new javax.swing.JButton();
        lbThongBao = new javax.swing.JLabel();
        jlbManv = new javax.swing.JLabel();
        tfMatkhaucu = new javax.swing.JPasswordField();
        tfMatkhaumoi = new javax.swing.JPasswordField();
        tfMatkhauxn = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Đổi Mật khẩu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/password_42px.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu Cũ");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Mật Khẩu Mới");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Nhập Lại Mật Khẩu Mới");

        jbXacnhan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbXacnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/ok_30px.png"))); // NOI18N
        jbXacnhan.setText("Xác Nhận");
        jbXacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXacnhanActionPerformed(evt);
            }
        });

        jbHuy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbHuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/cancel_30px.png"))); // NOI18N
        jbHuy.setText("Hủy");
        jbHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHuyActionPerformed(evt);
            }
        });

        lbThongBao.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jlbManv.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tfMatkhaucu.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfMatkhaucu.setText("111111111");

        tfMatkhaumoi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfMatkhaumoi.setText("111111111");

        tfMatkhauxn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfMatkhauxn.setText("111111111");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jlbManv, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfMatkhaucu, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(tfMatkhaumoi)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfMatkhauxn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jbXacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(jbHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jlbManv, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMatkhaucu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfMatkhaumoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfMatkhauxn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbThongBao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbXacnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbXacnhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXacnhanActionPerformed
        // TODO add your handling code here:
        if (checkRong()) {
            TaiKhoanDB db = new TaiKhoanDB();
            try {
                String matkhauc = tfMatkhaucu.getText();
                String matkhaum = tfMatkhaumoi.getText();
                String manv = jlbManv.getText();
                if(db.checkMatKhauCu(matkhauc,manv)){
                    if(db.doiMatKhau(matkhaum,manv)){
                        JOptionPane.showMessageDialog(null,"Đổi Mật Khẩu Thành Công");
                        this.dispose();
                    }else{
                        JOptionPane.showMessageDialog(null,"Đổi Mật Khẩu Thất Bại");
                    }
                }else{
                    lbThongBao.setText("Sai Mật Khẩu");
                    lbThongBao.setForeground(Color.red);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        }else{

        }
    }//GEN-LAST:event_jbXacnhanActionPerformed

    private void jbHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbHuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DoiMatKhau().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbHuy;
    private javax.swing.JButton jbXacnhan;
    private javax.swing.JLabel jlbManv;
    private javax.swing.JLabel lbThongBao;
    private javax.swing.JPasswordField tfMatkhaucu;
    private javax.swing.JPasswordField tfMatkhaumoi;
    private javax.swing.JPasswordField tfMatkhauxn;
    // End of variables declaration//GEN-END:variables

}
