/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlch.Model.HoaDon;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import qlch.Model.PhieuNhap.ChiTietPN;
import qlch.Model.PhieuNhap.ChiTietPNDB;

/**
 *
 * @author HiHi
 */
public class ChiTietHD extends javax.swing.JFrame {

    /**
     * Creates new form ChiTietHD
     */
      DefaultTableModel table;
    public ChiTietHD(String mahd) throws SQLException {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Chi Tiết Phiếu Nhập");
        CreateColumsTable();
         Populate(mahd);
         sort(); 
    }
    
      // Tạo tên cho cột
    private void CreateColumsTable(){
        table  = (DefaultTableModel) TableChiTietHoaDon.getModel();
        table.addColumn("Mã Phiếu Nhập");
        table.addColumn("Mã Sách");
        table.addColumn("Số Lượng");
        table.addColumn("Đơn Giá");
    }
    //Đổ Data cho bảng 
    private void Populate(String mahd) throws SQLException{   
        ChiTietHoaDonDB db = new ChiTietHoaDonDB();
          setDataToTable(db.getAllHoaDon(mahd),table);
    }
    //Đổ data từ arraylist vào row data
    private void setDataToTable(ArrayList<ChiTietHoaDon> data,DefaultTableModel table){
        table.setRowCount(0);
        for(ChiTietHoaDon s:data){
            table.addRow(new String[]{
             s.getMahd(),s.getMasach(),s.getSoluong(),s.getDongia()+" VNĐ"                  
            });
        }
    }
    //Sắp xếp theo cột
    private  void sort(){
        TableRowSorter<DefaultTableModel> sorter    = new TableRowSorter<DefaultTableModel>(table);
        TableChiTietHoaDon.setRowSorter(sorter);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableChiTietHoaDon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/news.png"))); // NOI18N
        jLabel1.setText("Chi Tiết  Hóa Đơn");

        TableChiTietHoaDon.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TableChiTietHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableChiTietHoaDon.setRowHeight(30);
        TableChiTietHoaDon.setSelectionBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setViewportView(TableChiTietHoaDon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableChiTietHoaDon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
