/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlch.View;

import java.awt.Font;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import qlch.Model.CuaHang.DanhSachHang.HoaDonHT;
import qlch.Model.CuaHang.DanhSachHang.HoaDonHTDB;
import qlch.Model.CuaHang.DanhSachHang.SanPhamHT;
import qlch.Model.CuaHang.DanhSachHang.SanPhamHTDB;
import qlch.Model.Sach.SachDB;

/**
 *
 * @author HiHi
 */
public class CuaHangPanel extends javax.swing.JPanel {
    /**
     * Creates new form CuaHangPanel
     */
    public CuaHangPanel() {
        initComponents();
        lbMaNhanVien.setText(MainControl.getManv());
        //Table Hiển Thị Sách
        CreateColumsTable1();
        Populate1();
        sort1();
        TableHTSach.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        //       
        
        //Table Hiển thị hóa đơn
        TableHThoadon.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
            CreateColumsTable2();
            Populate2();
            sort2();
            
        ////
    }
    int row1  = -1;
    DefaultTableModel table1;
    //****************Table Sach********************//
    // Xử Lý trong table hiển thị danh sách sách
    //////////////////////////////////
    private void CreateColumsTable1(){
        table1  = (DefaultTableModel) TableHTSach.getModel();
        table1.addColumn("Mã Sách");
        table1.addColumn("Đơn Giá");
        table1.addColumn("Số Lượng");
        
    }
    //Đổ Data cho bảng 
    private void Populate1() {   
        SanPhamHTDB db = new SanPhamHTDB();
        try {
            setDataToTable1(db.getAllHTSach(), table1);
            lbMaHD.setText("HD"+(db.MaHD()+1));
            lbMaKh.setText("KH"+(db.MaKH()+1));
            jlbTonghoadon.setText(db.tongTien(lbMaHD.getText()+"")+"");
            tfSDT.setText("");
            tfTenKH.setText("");
            tfDiaChi.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(CuaHangPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Đổ data từ arraylist vào row data
    private void setDataToTable1(ArrayList<SanPhamHT> data,DefaultTableModel table){
        table.setRowCount(0);
        for(SanPhamHT s :data){
            table.addRow(new String[]{
             s.getMasach(),s.getDongia(),s.getSoluong()
            });
        }
    }
    //Sắp xếp theo cột
    private  void sort1(){
        TableRowSorter<DefaultTableModel> sorter    = new TableRowSorter<DefaultTableModel>(table1);
        TableHTSach.setRowSorter(sorter);
    }
    ///////////////////////////////////
    int row2  = -1;
    DefaultTableModel table2;
    
    
    
    
    
    //****************Table Hoa Don********************//
    // Xử Lý trong table hiển thị danh sách chitiet hoadon
    //////////////////////////////////
    private void CreateColumsTable2(){
        table2  = (DefaultTableModel) TableHThoadon.getModel();
        table2.addColumn("Mã Hóa Đơn");
        table2.addColumn("Mã Sách");
        table2.addColumn("Số Lượng");
        table2.addColumn("Đơn Giá");
    }
    //Đổ Data cho bảng 
    private void Populate2() {   
        HoaDonHTDB db  =new HoaDonHTDB();
        try {
            setDataToTable2(db.getAllHoaDonHT(lbMaHD.getText()), table2);
        } catch (SQLException ex) {
            Logger.getLogger(CuaHangPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Đổ data từ arraylist vào row data
    private void setDataToTable2(ArrayList<HoaDonHT> data,DefaultTableModel table){
        table.setRowCount(0);
        for(HoaDonHT s :data){
            table.addRow(new String[]{
             s.getMahd(),s.getMasach(),s.getSoluong(),s.getDongia()+"VNĐ"
            });
        }
    }
    //Sắp xếp theo cột
    private  void sort2(){
        TableRowSorter<DefaultTableModel> sorter    = new TableRowSorter<DefaultTableModel>(table2);
        TableHThoadon.setRowSorter(sorter);
    }
    ///////////////////////////////////
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        TableSanPham = new javax.swing.JScrollPane();
        TableHTSach = new javax.swing.JTable();
        jlbAnh = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jlbDongia = new javax.swing.JLabel();
        lbTongtien = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        tfSoluong = new javax.swing.JTextField();
        JbtnXoa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableHThoadon = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jlbDongia1 = new javax.swing.JLabel();
        lbMaHD = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jlbDongia2 = new javax.swing.JLabel();
        lbMaNhanVien = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jlbDongia3 = new javax.swing.JLabel();
        lbMaKh = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jlbDongia4 = new javax.swing.JLabel();
        tfTenKH = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jlbDongia5 = new javax.swing.JLabel();
        tfDiaChi = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jlbDongia6 = new javax.swing.JLabel();
        tfSDT = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jlbDongia7 = new javax.swing.JLabel();
        jbtnNam = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jlbTonghoadon = new javax.swing.JLabel();
        jbtThanhtoan = new javax.swing.JButton();
        jbtThemsach = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jlbDongia8 = new javax.swing.JLabel();
        lbMasach = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jlbDongia9 = new javax.swing.JLabel();
        lbDongia = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1075, 690));

        TableSanPham.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        TableHTSach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TableHTSach.setForeground(new java.awt.Color(0, 0, 0));
        TableHTSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableHTSach.setGridColor(new java.awt.Color(255, 255, 255));
        TableHTSach.setRowHeight(35);
        TableHTSach.setSelectionBackground(new java.awt.Color(102, 102, 102));
        TableHTSach.setSelectionForeground(new java.awt.Color(204, 204, 204));
        TableHTSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHTSachMouseClicked(evt);
            }
        });
        TableSanPham.setViewportView(TableHTSach);

        jlbAnh.setBackground(new java.awt.Color(204, 153, 0));
        jlbAnh.setForeground(new java.awt.Color(153, 0, 102));
        jlbAnh.setBorder(new javax.swing.border.MatteBorder(null));
        jlbAnh.setPreferredSize(new java.awt.Dimension(277, 277));

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn Giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbTongtien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(42, Short.MAX_VALUE)))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Lượng Cần Mua", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel12.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfSoluong.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfSoluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSoluongActionPerformed(evt);
            }
        });
        tfSoluong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfSoluongKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addContainerGap())
        );

        JbtnXoa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        JbtnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/delete_forever_30px.png"))); // NOI18N
        JbtnXoa.setText("Xóa");
        JbtnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnXoaActionPerformed(evt);
            }
        });

        TableHThoadon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TableHThoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableHThoadon.setGridColor(new java.awt.Color(255, 255, 255));
        TableHThoadon.setRowHeight(35);
        TableHThoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableHThoadonMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableHThoadon);

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel13.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbMaHD.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbMaHD.setForeground(new java.awt.Color(0, 0, 0));
        lbMaHD.setText("jLabel1");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(lbMaHD, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã Nhân Viên", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel14.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbMaNhanVien.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbMaNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        lbMaNhanVien.setText("jLabel4");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lbMaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel14Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia2)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel15.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbMaKh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbMaKh.setForeground(new java.awt.Color(0, 0, 0));
        lbMaKh.setText("jLabel5");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMaKh, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addComponent(lbMaKh, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel15Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia3)
                    .addContainerGap(25, Short.MAX_VALUE)))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tên Khách Hàng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel16.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfTenKH.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(tfTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(122, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfTenKH, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia4)
                    .addContainerGap(27, Short.MAX_VALUE)))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Địa Chỉ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel17.setForeground(new java.awt.Color(0, 0, 0));
        jPanel17.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfDiaChi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbDongia5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
            .addComponent(tfDiaChi)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(tfDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlbDongia5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Điện Thoại", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel18.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        tfSDT.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbDongia6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(tfSDT)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(tfSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jlbDongia6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Giới Tính", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel19.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        buttonGroup1.add(jbtnNam);
        jbtnNam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnNam.setText("Nam");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRadioButton2.setText("Nữ");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnNam)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jRadioButton2)
                .addGap(29, 29, 29))
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia7, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(93, Short.MAX_VALUE)))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jRadioButton2)
                .addComponent(jbtnNam))
            .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel19Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia7)
                    .addContainerGap(23, Short.MAX_VALUE)))
        );

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jLabel2.setText("Tổng Tiền :");

        jlbTonghoadon.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jlbTonghoadon.setText(" 10000000 VNĐ");

        jbtThanhtoan.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtThanhtoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/ok_30px.png"))); // NOI18N
        jbtThanhtoan.setText("Thanh Toán");
        jbtThanhtoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThanhtoanActionPerformed(evt);
            }
        });

        jbtThemsach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtThemsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/add_30px.png"))); // NOI18N
        jbtThemsach.setText("Thêm Vào Hóa Đơn");
        jbtThemsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThemsachActionPerformed(evt);
            }
        });

        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mã Sách", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel20.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbMasach.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbMasach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia8, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMasach, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel20Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia8)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đơn Giá", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel21.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        jlbDongia9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lbDongia.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbDongia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jlbDongia9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbDongia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel21Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jlbDongia9)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jbtThemsach)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JbtnXoa)
                                .addGap(60, 60, 60)
                                .addComponent(jbtThanhtoan)
                                .addGap(24, 24, 24))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbTonghoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(TableSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 7, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {JbtnXoa, jbtThanhtoan});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbTonghoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtThanhtoan)
                                .addComponent(JbtnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jbtThemsach)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlbAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(166, 166, 166))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(TableSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(452, Short.MAX_VALUE))
        );

        jPanel12.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void tfSoluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSoluongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfSoluongActionPerformed
    
    
    //****************Table Hoa Don********************//
    private void JbtnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnXoaActionPerformed
        // TODO add your handling code here:
        if(row2!=-1){
            SanPhamHTDB db = new SanPhamHTDB();
            String s = TableHThoadon.getModel().getValueAt(row2,0)+"";
             String s1 = TableHThoadon.getModel().getValueAt(row2,1)+"";
             String s2 = " + "+TableHThoadon.getModel().getValueAt(row2,2)+"";
            if(db.xoaChitiethoadon(s,s1)&&db.capNhatSoLuong(s1, s2)){
            Populate2();
            sort2();
            }else{
                JOptionPane.showMessageDialog(null,"Xóa Không Thành Công");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Bạn cần chọn sản phẩm muốn xóa");
        }
    }//GEN-LAST:event_JbtnXoaActionPerformed

   //****************Table Sach********************//
    //Sự kiện click vào 1 ô nào đó trong table TableHTSach
    private void TableHTSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHTSachMouseClicked
        // TODO add your handling code here:
        row1  = TableHTSach.getSelectedRow(); 
        displaytoTextField1(row1);  //trả data về textfield
        showImage(row1); 
    }//GEN-LAST:event_TableHTSachMouseClicked
    //****************Table Sach********************//
    private void tfSoluongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSoluongKeyReleased
        // TODO add your handling code here:
        String query = tfSoluong.getText().toLowerCase();
        if(!query.equals(""))
        {try{
            float sl = Float.parseFloat(query);
            lbTongtien.setText(Float.parseFloat(lbDongia.getText())*sl+"");
        }catch (Exception e){
            tfSoluong.setText("1");
            lbTongtien.setText(lbDongia.getText());
        }
        }
    }//GEN-LAST:event_tfSoluongKeyReleased
//****************Table Sach********************//
    private void jbtThemsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThemsachActionPerformed
        // TODO add your handling code here:
       if(tfSoluong.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Bạn không được bỏ trống số lượng");
       }else if(Integer.parseInt(tfSoluong.getText()) > Integer.parseInt(TableHTSach.getModel().getValueAt(row1,2)+"")){
           JOptionPane.showMessageDialog(null,"Số Lượng Hàng Trong Kho Không Đủ");
       }else{
        SanPhamHTDB db = new SanPhamHTDB();
        String mahd = lbMaHD.getText();
        String masach = lbMasach.getText();
        String soluong =tfSoluong.getText();
        String soluong2 = " - "+soluong;
        String dongia = lbDongia.getText();
        if(db.themSanPham(mahd,masach,soluong,dongia) && db.capNhatSoLuong(masach,soluong2)){
            Populate2();
            sort2();
            try {
                jlbTonghoadon.setText(db.tongTien(lbMaHD.getText()+"")+"");
            } catch (SQLException ex) {
                System.out.println(ex);
            }
        }else{
            JOptionPane.showMessageDialog(null,"Thêm Không Thành Công \n"
                    + "Sản Phẩm Đã Tồn Tại Trong Hóa Đơn");
        }
        }
    }//GEN-LAST:event_jbtThemsachActionPerformed
     //****************Table Hoa Don********************//
    private void TableHThoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableHThoadonMouseClicked
        // TODO add your handling code here:
                row2  = TableHThoadon.getSelectedRow(); 
    }//GEN-LAST:event_TableHThoadonMouseClicked
    
    private boolean checkRong(){
        String gt = jbtnNam.isSelected()?"Nam":"Nữ";
        String tenkh = tfTenKH.getText();
        String diachi =tfDiaChi.getText();
        String sdt =tfSDT.getText();
        if(tenkh.equals("")){
            JOptionPane.showMessageDialog(null,"Bạn Cần Nhập Tên Khách Hàng");
            return  false;
        }else if(diachi.equals("")){
            JOptionPane.showMessageDialog(null,"Bạn Cần Nhập Tên Địa Chỉ");
            return  false;
        }else if(gt.equals("")){
            JOptionPane.showMessageDialog(null,"Bạn Cần Nhập Giới Tính");
            return  false;
        }else if (sdt.equals("")){
            JOptionPane.showMessageDialog(null,"Bạn Cần Nhập Số Điện Thoại");
            return  false;
        }else{
            try{    
                  long sdt1 = Long.parseLong(sdt);
            }catch (Exception e){
                return false;
            }
            return true;
        }
    }


    //****************Table Hoa Don********************//
    private void jbtThanhtoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThanhtoanActionPerformed
        // TODO add your handling code here:
        if(checkRong()){
        String gt = jbtnNam.isSelected()?"Nam":"Nữ";
        String tenkh = tfTenKH.getText();
        String diachi =tfDiaChi.getText();
        String sdt =tfSDT.getText();
        String manv= lbMaNhanVien.getText();
        String makh = lbMaKh.getText();
        int tongtien = (int)Float.parseFloat(lbTongtien.getText());
        String tongtien1 = tongtien+"";
        String mahd = lbMaHD.getText();
            HoaDonHTDB db = new HoaDonHTDB();
            SanPhamHTDB db1= new SanPhamHTDB();
            if(db.themHoaDon(makh,tenkh,diachi,sdt,gt,mahd,manv,tongtien1)){
                 Populate1();
                 sort1();
                 Populate2();
                 sort2();
            }else{
                JOptionPane.showMessageDialog(null,"Nhập Dữ Liệu Không Thành Công");
            }
        }
    }//GEN-LAST:event_jbtThanhtoanActionPerformed
   //****************Table Sach********************//                                   
    //lấy tên file ảnh từ database xuất lên màn hình 
    private void showImage(int row){
       try {
           SachDB db =new SachDB();
           String s = TableHTSach.getModel().getValueAt(row,0)+""; //lấy mã sách
           s =  db.showImage(s); //lấy tên của file ảnh
            jlbAnh.setSize(277,277);
        // show hình ảnh
        int w   = jlbAnh.getWidth();
        int h = jlbAnh.getHeight();      
        ImageIcon img = new ImageIcon(getClass().getResource("/qlch/Image/Sach/"+s));
        Image imgScaled = img.getImage().getScaledInstance(w, h, Image.SCALE_DEFAULT);
        jlbAnh.setIcon(new ImageIcon(imgScaled));
        } catch (Exception e) {
        }
    }
//****************Table Sach********************//
    //Hiển thị thông tin vào các ô trống của 
    private void displaytoTextField1(int row){
        lbMasach.setText(TableHTSach.getModel().getValueAt(row,0)+"");
        float dongia = Float.parseFloat(TableHTSach.getModel().getValueAt(row,1)+"");
        lbDongia.setText(dongia+"");
        float soluong  = 1;
        tfSoluong.setText("1");
        float tongtien = dongia*soluong;
        lbTongtien.setText(tongtien+"");
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnXoa;
    private javax.swing.JTable TableHTSach;
    private javax.swing.JTable TableHThoadon;
    private javax.swing.JScrollPane TableSanPham;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtThanhtoan;
    private javax.swing.JButton jbtThemsach;
    private javax.swing.JRadioButton jbtnNam;
    private javax.swing.JLabel jlbAnh;
    private javax.swing.JLabel jlbDongia;
    private javax.swing.JLabel jlbDongia1;
    private javax.swing.JLabel jlbDongia2;
    private javax.swing.JLabel jlbDongia3;
    private javax.swing.JLabel jlbDongia4;
    private javax.swing.JLabel jlbDongia5;
    private javax.swing.JLabel jlbDongia6;
    private javax.swing.JLabel jlbDongia7;
    private javax.swing.JLabel jlbDongia8;
    private javax.swing.JLabel jlbDongia9;
    private javax.swing.JLabel jlbTonghoadon;
    private javax.swing.JLabel lbDongia;
    private javax.swing.JLabel lbMaHD;
    private javax.swing.JLabel lbMaKh;
    private javax.swing.JLabel lbMaNhanVien;
    private javax.swing.JLabel lbMasach;
    private javax.swing.JLabel lbTongtien;
    private javax.swing.JTextField tfDiaChi;
    private javax.swing.JTextField tfSDT;
    private javax.swing.JTextField tfSoluong;
    private javax.swing.JTextField tfTenKH;
    // End of variables declaration//GEN-END:variables
}
