/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlch.View;

import java.awt.Font;
import java.awt.Image;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import qlch.Model.Sach.Sach;
import qlch.Model.Sach.SachDB;
import qlch.Model.Sach.SuaSach;
import qlch.Model.Sach.ThemSach;

/**
 *
 * @author HiHi
 */
public class DSSach extends javax.swing.JPanel {

    /**
     * Creates new form SanPhamPanel
     */
    int row  = -1;
    DefaultTableModel table;
    public DSSach() throws SQLException {
        setSize(1075,690);
        initComponents();
        CreateColumsTable();
        TableSach.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        Populate();
        sort();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // Tạo tên cho cột
    private void CreateColumsTable(){
        table  = (DefaultTableModel) TableSach.getModel();
        table.addColumn("Mã Sách");
        table.addColumn("Tên Sách");
        table.addColumn("Tác Giả");
        table.addColumn("Nhà Xuất Bản");
        table.addColumn("Kích Thước");
        table.addColumn("Số Trang");
        
    }
    //Đổ Data cho bảng 
    private void Populate() throws SQLException{   
        SachDB db =new SachDB();
          setDataToTable(db.getAllSach(),table);
    }
    //Đổ data từ arraylist vào row data
    private void setDataToTable(ArrayList<Sach> data,DefaultTableModel table){
        table.setRowCount(0);
        for(Sach s :data){
            table.addRow(new String[]{
             s.getMasach(),s.getTensach(),s.getTacgia(),s.getNhaxb(),s.getKichthuoc(),s.getSotrang()
            });
        }
    }
    //Sắp xếp theo cột
    private  void sort(){
        TableRowSorter<DefaultTableModel> sorter    = new TableRowSorter<DefaultTableModel>(table);
        TableSach.setRowSorter(sorter);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jcTimkiem = new javax.swing.JComboBox<>();
        jpTimkiem = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jlbImage = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        tfTensach = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        tfMasach = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        tfTacgia = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        tfNhaxuatban = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        tfKichthuoc = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        tfSotrang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableSach = new javax.swing.JTable();
        jbXoa = new javax.swing.JButton();
        jbThem = new javax.swing.JButton();
        jbSua = new javax.swing.JButton();

        setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1075, 690));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tất Cả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));

        jcTimkiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jcTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        jcTimkiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Mã Sách", "Tên Sách", "Tác Giả", "Nhà Xuất Bản" }));
        jcTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcTimkiemActionPerformed(evt);
            }
        });

        jpTimkiem.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tất Cả", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jpTimkiem.setForeground(new java.awt.Color(0, 0, 0));
        jpTimkiem.setToolTipText("");
        jpTimkiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTextField1.setAutoscrolls(false);
        jTextField1.setBorder(null);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpTimkiemLayout = new javax.swing.GroupLayout(jpTimkiem);
        jpTimkiem.setLayout(jpTimkiemLayout);
        jpTimkiemLayout.setHorizontalGroup(
            jpTimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpTimkiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpTimkiemLayout.setVerticalGroup(
            jpTimkiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpTimkiemLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jcTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jcTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jpTimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        jPanel7.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel7.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbImage, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Trang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel8.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfTensach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfTensach.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTensach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTensachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfTensach, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(tfTensach)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Trang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel9.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfMasach.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfMasach.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfMasach, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(tfMasach)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Trang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel10.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfTacgia.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfTacgia.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(tfTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Trang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel11.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfNhaxuatban.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfNhaxuatban.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNhaxuatban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNhaxuatbanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfNhaxuatban, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(tfNhaxuatban, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Trang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel12.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfKichthuoc.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfKichthuoc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfKichthuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(tfKichthuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Số Trang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel13.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N

        tfSotrang.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        tfSotrang.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfSotrang, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(tfSotrang, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jScrollPane1.setOpaque(false);
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        TableSach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TableSach.setForeground(new java.awt.Color(0, 0, 0));
        TableSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TableSach.setGridColor(new java.awt.Color(255, 255, 255));
        TableSach.setRowHeight(40);
        TableSach.setSelectionBackground(new java.awt.Color(51, 51, 51));
        TableSach.setSelectionForeground(new java.awt.Color(204, 204, 204));
        TableSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSach);

        jbXoa.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jbXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/delete_forever_30px.png"))); // NOI18N
        jbXoa.setText("Xóa");
        jbXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbXoaActionPerformed(evt);
            }
        });

        jbThem.setBackground(new java.awt.Color(255, 255, 255));
        jbThem.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jbThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/add_30px.png"))); // NOI18N
        jbThem.setText("Thêm");
        jbThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbThemActionPerformed(evt);
            }
        });

        jbSua.setFont(new java.awt.Font("Arial", 0, 15)); // NOI18N
        jbSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlch/Image/GiaoDien/maintenance_30px.png"))); // NOI18N
        jbSua.setText("Sửa");
        jbSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jbXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbThem)
                                .addGap(76, 76, 76)
                                .addComponent(jbSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(279, 279, 279))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbXoa)
                            .addComponent(jbThem)
                            .addComponent(jbSua)))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane1MouseClicked
    //lấy gia trị row đang click
    private void TableSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSachMouseClicked
        // TODO add your handling code here:
        row  = TableSach.getSelectedRow(); 
        displaytoTextField(row);  //trả data về textfield
        showImage(row); 
    }//GEN-LAST:event_TableSachMouseClicked
    //lấy tên file ảnh từ database xuất lên màn hình
    private void showImage(int row){
       try {
           SachDB db =new SachDB();
           String s = TableSach.getModel().getValueAt(row,0)+""; //lấy mã sách
           s =  db.showImage(s); //lấy tên của file ảnh
            jlbImage.setSize(284,284);
        // show hình ảnh
        int w   = jlbImage.getWidth();
        int h = jlbImage.getHeight();      
        ImageIcon img = new ImageIcon(getClass().getResource("/qlch/Image/Sach/"+s));
        Image imgScaled = img.getImage().getScaledInstance(w, h, Image.SCALE_DEFAULT);
        jlbImage.setIcon(new ImageIcon(imgScaled));
        } catch (Exception e) {
        }
    }
    private void tfTensachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTensachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTensachActionPerformed

    private void tfNhaxuatbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNhaxuatbanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNhaxuatbanActionPerformed
    //filter dữ liệu từ câu query lấy từ textfiel event
    private void  searchTable(String query) throws SQLException{
        int x = jcTimkiem.getSelectedIndex();
        String tencot= null;
        switch(x){
            case 1: tencot = "MaSach";
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Mã Sách"));
            break;
            case 2 : tencot = "TenSach";
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Tên Sách"));
            break;
            case 3 : tencot = "TacGia";
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Tác Giả"));
            break;
            case 4 : tencot = "NhaXB";
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Nhà Xuất Bản"));
            break;
            default: tencot = "TenSach";
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Tất Cả"));
        }
        SachDB db =new SachDB();
        setDataToTable(db.search(tencot, query),table);
        sort();
    }
    //event nhập vào text field gửi querry về
    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        try {
            // TODO add your handling code here:
            String query = jTextField1.getText().toLowerCase();
            searchTable(query);
        } catch (SQLException ex) {
            Logger.getLogger(DSSach.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextField1KeyReleased
    //event lúc chọn combobox gửi đổi tượng về query để thực hiện filter
    private void jcTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcTimkiemActionPerformed
        // TODO add your handling code here:
                int x = jcTimkiem.getSelectedIndex();
        switch(x){
            case 1: 
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Mã Sách"));
            break;
            case 2 :
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Tên Sách"));
            break;
            case 3 : 
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Tác Giả"));
            break;
            case 4 : 
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Nhà Xuất Bản"));
            break;
            default:
            jpTimkiem.setBorder(BorderFactory.createTitledBorder("Tất Cả"));
        }
    }//GEN-LAST:event_jcTimkiemActionPerformed
    
    
    //xóa đối tượng đang được chọn
    private void jbXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbXoaActionPerformed
        // TODO add your handling code here:
        if (row == -1){
            JOptionPane.showMessageDialog(null,"Bạn cần chọn đối tượng cần xóa","Lỗi", HEIGHT);
        }else {           
            int x = JOptionPane.showConfirmDialog (null, "Bạn có chắc chắn xóa đối tượng này","Cảnh báo",JOptionPane.YES_NO_CANCEL_OPTION);
            if (x == 0){
                String s = TableSach.getModel().getValueAt(row,0)+"";
                try {
                    SachDB db =new SachDB();
                    db.xoa(s);
                    Populate();
                     sort();
                    JOptionPane.showMessageDialog(null,"Xóa Thành Công","Success",HEIGHT);
                } catch (SQLException ex) {
                    Logger.getLogger(DSSach.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_jbXoaActionPerformed
    //Thêm 1 đôi tượng mới
    private void jbThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbThemActionPerformed
        // TODO add your handling code here:
        ThemSach ts = new ThemSach();
        ts.setVisible(true);
    }//GEN-LAST:event_jbThemActionPerformed

    private void jbSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSuaActionPerformed
        // TODO add your handling code here:
      if(row == -1){
          JOptionPane.showMessageDialog(null,"Bạn Cần Chọn Đối Tượng Cần Sửa");
      }else{
          //Gửi các dừ liệu về textfield trong SuasachJfram
        SachDB db = new SachDB();
        SuaSach ts = new SuaSach();
        String masach = TableSach.getModel().getValueAt(row,0)+"";
        String tensach = TableSach.getModel().getValueAt(row,1)+"";
        String tacgia= TableSach.getModel().getValueAt(row,2)+"";
        String nhaxb = TableSach.getModel().getValueAt(row,3)+"";
        String kichthuoc = TableSach.getModel().getValueAt(row,4)+"";
        String sotrang = TableSach.getModel().getValueAt(row,5)+"";
        try {
            String url =  db.showImage(masach);
            ts.setTextField(url,kichthuoc,masach,nhaxb,sotrang,tacgia,tensach);
        } catch (SQLException ex) {          
        }
         ts.setVisible(true);
      }
    }//GEN-LAST:event_jbSuaActionPerformed
    private void displaytoTextField(int row){
        //lúc click thì hiện ra thông tin textfield ở sanphampanel
        tfMasach.setText(TableSach.getModel().getValueAt(row,0)+"");
        tfTensach.setText(TableSach.getModel().getValueAt(row,1)+"");
        tfTacgia.setText(TableSach.getModel().getValueAt(row,2)+"");
        tfNhaxuatban.setText(TableSach.getModel().getValueAt(row,3)+"");
        tfKichthuoc.setText(TableSach.getModel().getValueAt(row,4)+"");
        tfSotrang.setText(TableSach.getModel().getValueAt(row,5)+"");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableSach;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbSua;
    private javax.swing.JButton jbThem;
    private javax.swing.JButton jbXoa;
    private javax.swing.JComboBox<String> jcTimkiem;
    private javax.swing.JLabel jlbImage;
    private javax.swing.JPanel jpTimkiem;
    private javax.swing.JTextField tfKichthuoc;
    private javax.swing.JTextField tfMasach;
    private javax.swing.JTextField tfNhaxuatban;
    private javax.swing.JTextField tfSotrang;
    private javax.swing.JTextField tfTacgia;
    private javax.swing.JTextField tfTensach;
    // End of variables declaration//GEN-END:variables
}
